### ISSUE TITLE
1.7.1 action broken PyYAML Dependency

### ISSUE THREAD

**Issue by jstewart612** [reviewdog/action-yamllint#27]
```
#6 [4/5] RUN pip install yamllint
  #6 sha256:597969989b7cd3daf0e2626c8d68e062fc11973f3f2d05109fe1f4cd2fc87f8c
  #6 1.750 Collecting yamllint
  #6 1.816   Downloading yamllint-1.32.0-py3-none-any.whl (65 kB)
  #6 1.839      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 2.6 MB/s eta 0:00:00
  #6 1.874 Collecting pathspec>=0.5.3 (from yamllint)
  #6 1.884   Downloading pathspec-0.11.1-py3-none-any.whl (29 kB)
  #6 1.938 Collecting pyyaml (from yamllint)
  #6 1.948   Downloading PyYAML-6.0.tar.gz (124 kB)
  #6 1.963      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 8.6 MB/s eta 0:00:00
  #6 2.076   Installing build dependencies: started
  #6 4.406   Installing build dependencies: finished with status 'done'
  #6 4.407   Getting requirements to build wheel: started
  #6 4.606   Getting requirements to build wheel: finished with status 'error'
  #6 4.611   error: subprocess-exited-with-error
  #6 4.611   
  #6 4.611   × Getting requirements to build wheel did not run successfully.
  #6 4.611   │ exit code: 1
  #6 4.611   ╰─> [54 lines of output]
  #6 4.611       running egg_info
  #6 4.611       writing lib/PyYAML.egg-info/PKG-INFO
  #6 4.611       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
  #6 4.611       writing top-level names to lib/PyYAML.egg-info/top_level.txt
  #6 4.611       Traceback (most recent call last):
  #6 4.611         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
  #6 4.611           main()
  #6 4.611         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line [335](https://github.com/rentpath/kubernetes-argo-cd/actions/runs/5579028295/jobs/10194023506#step:3:335), in main
  #6 4.611           json_out['return_val'] = hook(**hook_input['kwargs'])
  #6 4.611                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  #6 4.611         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
  #6 4.611           return hook(config_settings)
  #6 4.611                  ^^^^^^^^^^^^^^^^^^^^^
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
  #6 4.611           return self._get_build_requires(config_settings, requirements=['wheel'])
  #6 4.611                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
  #6 4.611           self.run_setup()
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
  #6 4.611           exec(code, locals())
  #6 4.611         File "<string>", line 288, in <module>
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
  #6 4.611           return distutils.core.setup(**attrs)
  #6 4.611                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
  #6 4.611           return run_commands(dist)
  #6 4.611                  ^^^^^^^^^^^^^^^^^^
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
  #6 4.611           dist.run_commands()
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
  #6 4.611           self.run_command(cmd)
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
  #6 4.611           super().run_command(command)
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
  #6 4.611           cmd_obj.run()
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
  #6 4.611           self.find_sources()
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
  #6 4.611           mm.run()
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
  #6 4.611           self.add_defaults()
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
  #6 4.611           sdist.add_defaults(self)
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
  #6 4.611           super().add_defaults()
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
  #6 4.611           self._add_defaults_ext()
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line [336](https://github.com/rentpath/kubernetes-argo-cd/actions/runs/5579028295/jobs/10194023506#step:3:336), in _add_defaults_ext
  #6 4.611           self.filelist.extend(build_ext.get_source_files())
  #6 4.611                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  #6 4.611         File "<string>", line 204, in get_source_files
  #6 4.611         File "/tmp/pip-build-env-cczs3zxf/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
  #6 4.611           raise AttributeError(attr)
  #6 4.611       AttributeError: cython_sources
  #6 4.611       [end of output]
  #6 4.611   
  #6 4.611   note: This error originates from a subprocess, and is likely not a problem with pip.
  #6 4.612 error: subprocess-exited-with-error
  #6 4.612 
  #6 4.612 × Getting requirements to build wheel did not run successfully.
  #6 4.612 │ exit code: 1
  #6 4.612 ╰─> See above for output.
  #6 4.612 
  #6 4.612 note: This error originates from a subprocess, and is likely not a problem with pip.
  #6 4.623 
  #6 4.623 [notice] A new release of pip is available: 23.1.2 -> 23.2
  #6 4.623 [notice] To update, run: pip install --upgrade pip
  #6 ERROR: process "/bin/sh -c pip install yamllint" did not complete successfully: exit code: 1
```

**Comment by jstewart612** [comment]
Source of error:

https://github.com/reviewdog/action-yamllint/blob/4e58de14a49ba0b563506a5b0a6429a210f633ec/Dockerfile#L8C1-L9C1

Unbounded let-it-rip-every-time-it-runs keeps things nice and updated normally but sometimes this creates problems like this one.

Probably want to version pin in a couple of places.

**Comment by st0ck** [comment]
I created a temporary fix for our workflows https://github.com/reviewdog/action-yamllint/compare/master...st0ck:action-yamllint:master

More info about the issue could be found here https://github.com/yaml/pyyaml/issues/601

**Comment by javierjulio** [comment]
@st0ck do you just want to open a PR with that change if it is working? I was going to take a shot at this.

**Comment by pdeschen** [comment]
> Probably want to version pin in a couple of places.

Yeah. hadolint would have report this on the Dockerfile :-)
